aves = {
    'aguililla_cola_roja': {
        'ojos': ['negros', 'amarillos'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': [],
        'vientre': ['blanco'],
        'cabeza': [],
        'garganta': [],
        'espalda': ['gris'],
        'alas': ['cafes', 'rojas', 'blancas'],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'cernicalo_americano': {
        'ojos': ['negros'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': ['naranja'],
        'auriculares': [],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': ['roja', 'negra'],
        'alas': ['azules'],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'chara_de_san_blas_adulto': {
        'ojos': ['negros'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['negro'],
        'vientre': ['negro'],
        'cabeza': ['negra'],
        'garganta': ['negra'],
        'espalda': ['azul'],
        'alas': ['azules'],
        'cola': ['azul', 'morada'],
        'patas': ['amarillas'],
        'tarso': ['amarillo'],
        'rabadilla': ['azul'],
    },
    'chipe_coronada_anaranjada': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': [],
        'garganta': ['amarilla'],
        'espalda': [],
        'alas': ['amarillas'],
        'cola': ['amarilla'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'garceta_pie_dorado': {
        'ojos': ['amarillos'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': ['amarillas', 'naranjas'],
        'cuerpo': ['blanco'],
        'nuca': [],
        'auriculares': [],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': [],
        'patas': ['amarillas'],
        'tarso': ['negro'],
        'rabadilla': [],
    },
    'garza_ganadera_no_reproductiva': {
        'ojos': ['amarillos'],
        'pico': ['amarillo'],
        'antifaz': [],
        'frente': [],
        'loras': ['amarillas', 'naranjas'],
        'cuerpo': ['blanco'],
        'nuca': [],
        'auriculares': [],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': [],
        'patas': ['negras'],
        'tarso': ['negro'],
        'rabadilla': [],
    },
    'gavilan_pecho_rufo': {
        'ojos': ['rojos'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': ['grises', 'rojos'],
        'pecho': ['blanco'],
        'vientre': ['blanco'],
        'cabeza': [],
        'garganta': [],
        'espalda': ['gris'],
        'alas': ['grises'],
        'cola': ['gris'],
        'patas': ['amarillas'],
        'tarso': ['amarillo'],
        'rabadilla': [],
    },
    'loro_corona_lira': {
        'ojos': ['amarillos'],
        'pico': ['amarillo'],
        'antifaz': [],
        'frente': ['rojo'],
        'loras': [],
        'cuerpo': ['verde'],
        'nuca': ['naranja'],
        'auriculares': ['azules', 'lilas'],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': ['roja', 'negra'],
        'alas': ['verdes'],
        'cola': [],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'luis_bienteveo': {
        'ojos': ['negros', 'amarillos'],
        'pico': ['negro'],
        'antifaz': ['negro'],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': ['blanca'],
        'garganta': ['blanca'],
        'espalda': ['cafe'],
        'alas': ['rojas'],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'mosquero_de_hammond': {
        'ojos': ['negro'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['gris'],
        'vientre': [],
        'cabeza': ['gris'],
        'garganta': ['gris'],
        'espalda': [],
        'alas': [],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'mulato_azul': {
        'ojos': ['rojos'],
        'pico': ['gris'],
        'antifaz': [],
        'frente': [],
        'loras': ['negras'],
        'cuerpo': ['azul'],
        'nuca': [],
        'auriculares': ['negros'],
        'pecho': ['azul'],
        'vientre': [],
        'cabeza': ['azul'],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'papamoscas_llanero': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['gris'],
        'vientre': [],
        'cabeza': ['gris'],
        'garganta': ['gris'],
        'espalda': ['gris'],
        'alas': [],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
    'tangara_capucha_roja': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': ['amarilla'],
        'garganta': [],
        'espalda': [],
        'alas': ['negras'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
    },
}
