# 25 aves pre-cargadas al sistema

aves = {
    'aguililla_cola_roja': {
        'ojos': ['negros', 'amarillos'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': [],
        'vientre': ['blanco'],
        'cabeza': [],
        'garganta': [],
        'espalda': ['gris'],
        'alas': ['cafes', 'rojas', 'blancas'],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [54],
        'habitat': ['áreas abiertas (valles, praderas y cultivos), bosques y cableado eléctrico paralelo a carreteras'],
        'comida': ['roedores, aves, reptiles, anfibios y ocasionalmente carroña']
    },
    'bolsero_dorso_rayado': {
        'ojos': ['negros'],
        'pico': [],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['naranja'],
        'vientre': ['naranja'],
        'cabeza': ['naranja'],
        'garganta': [],
        'espalda': ['naranja', 'negra'],
        'alas': ['negras'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [22],
        'habitat': ['bosques templados y tropicales, ecotonos de bosques, arbolados dispersos'],
        'comida': ['insectos y frutos']
    },
    'bolsero_encapuchado': {
        'ojos': ['negros'],
        'pico': ['gris'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': ['amarillo'],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': ['amarilla'],
        'garganta': [],
        'espalda': ['negra'],
        'alas': ['negras'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [19],
        'habitat': ['bosques de pino-encino, arbolados dispersos y matorrales'],
        'comida': ['insectos, frutos y néctar']
    },
    'cernicalo_americano': {
        'ojos': ['negros'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': ['naranja'],
        'auriculares': [],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': ['roja', 'negra'],
        'alas': ['azules'],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [25],
        'habitat': ['áreas abiertas (valles, praderas, cultivos), bordes de bosques, matorrales y ciudades'],
        'comida': ['insectos, mamíferos pequeños, aves y reptiles']
    },
    'chara_de_san_blas_adulto': {
        'ojos': ['negros'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['negro'],
        'vientre': ['negro'],
        'cabeza': ['negra'],
        'garganta': ['negra'],
        'espalda': ['azul'],
        'alas': ['azules'],
        'cola': ['azul', 'morada'],
        'patas': ['amarillas'],
        'tarso': ['amarillo'],
        'rabadilla': ['azul'],
        'tamanio': [32],
        'habitat': ['bosques tropicales, manglares y matorrales costeros'],
        'comida': ['insectos, arañas, pequeñas lagartijas, mamíferos, semillas y frutos']
    },
    'chipe_coronada_anaranjada': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': [],
        'garganta': ['amarilla'],
        'espalda': [],
        'alas': ['amarillas'],
        'cola': ['amarilla'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [14],
        'habitat': ['bosques de pino-encino, bosques tropicales, bosques de encino, vegetación riparia y zonas arboladas en asentamientos humanos'],
        'comida': ['insectos y pequeños frutos']
    },
    'colibrí_corona_violeta': {
        'ojos': ['negros'],
        'pico': ['rojo', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': ['verde'],
        'auriculares': [],
        'pecho': ['blanco'],
        'vientre': ['blanco'],
        'cabeza': ['violeta'],
        'garganta': ['blanca'],
        'espalda': ['verde'],
        'alas': ['negras'],
        'cola': ['verde'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [11],
        'habitat': ['matorrales, bosques, vegetación riparia y áreas semiabiertas'],
        'comida': ['néctar floral, en ocasiones consume insectos y rara vez pequeñas arañas']
    },
    'garceta_pie_dorado': {
        'ojos': ['amarillos'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': ['amarillas', 'naranjas'],
        'cuerpo': ['blanco'],
        'nuca': [],
        'auriculares': [],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': [],
        'patas': ['amarillas'],
        'tarso': ['negro'],
        'rabadilla': [],
        'tamanio': [59],
        'habitat': ['lagos, pantanos, charcas, playas y manglares'],
        'comida': ['peces, insectos y crustáceos']
    },
    'garza_ganadera_no_reproductiva': {
        'ojos': ['amarillos'],
        'pico': ['amarillo'],
        'antifaz': [],
        'frente': [],
        'loras': ['amarillas', 'naranjas'],
        'cuerpo': ['blanco'],
        'nuca': [],
        'auriculares': [],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': [],
        'patas': ['negras'],
        'tarso': ['negro'],
        'rabadilla': [],
        'tamanio': [50],
        'habitat': ['granjas, sembradíos y cuerpos de agua (lagos, pantanos)'],
        'comida': ['insectos, huevos de otras aves y en ocasiones peces']
    },
    'gavilan_pecho_rufo': {
        'ojos': ['rojos'],
        'pico': ['gris', 'negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': ['grises', 'rojos'],
        'pecho': ['blanco'],
        'vientre': ['blanco'],
        'cabeza': [],
        'garganta': [],
        'espalda': ['gris'],
        'alas': ['grises'],
        'cola': ['gris'],
        'patas': ['amarillas'],
        'tarso': ['amarillo'],
        'rabadilla': [],
        'tamanio': [30],
        'habitat': ['bosques templados (pino, pino-encino, encino)'],
        'comida': ['aves pequeñas y roedores']
    },
    'jilguero_dominicano': {
        'ojos': ['negros'],
        'pico': ['rosa'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': ['negra'],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': ['negra'],
        'garganta': ['amarilla'],
        'espalda': ['negra'],
        'alas': ['negras'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [10],
        'habitat': ['bosques tropicales y templados, ecotonos de bosques, pastizales arbolados y campos de cultivo'],
        'comida': ['semillas e insectos']
    },
    'lechuza_de_campanario': {
        'ojos': ['negros'],
        'pico': ['gris', 'rosa'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': ['naranja', 'gris'],
        'nuca': [],
        'auriculares': [],
        'pecho': ['blanco'],
        'vientre': ['blanco'],
        'cabeza': ['blanca'],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': [],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [40],
        'habitat': ['areas abiertas, borde de bosques semiáridos a semihúmedos, granjas, graneros y zonas urbanas (en parques, campanarios, casas abandonadas, bodegas)'],
        'comida': ['mamíferos pequeños como ratas, ratones, conejos y musarañas, aves pequeñas y lagartijas.']
    },
    'loro_corona_lira': {
        'ojos': ['amarillos'],
        'pico': ['amarillo'],
        'antifaz': [],
        'frente': ['rojo'],
        'loras': [],
        'cuerpo': ['verde'],
        'nuca': ['naranja'],
        'auriculares': ['azules', 'lilas'],
        'pecho': [],
        'vientre': [],
        'cabeza': [],
        'garganta': [],
        'espalda': ['roja', 'negra'],
        'alas': ['verdes'],
        'cola': [],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [32],
        'habitat': ['bosques tropicales (selvas), bordes de bosque de pino-encino y manglares'],
        'comida': ['semillas']
    },
    'luis_bienteveo': {
        'ojos': ['negros', 'amarillos'],
        'pico': ['negro'],
        'antifaz': ['negro'],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': ['blanca'],
        'garganta': ['blanca'],
        'espalda': ['cafe'],
        'alas': ['rojas'],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [25],
        'habitat': ['áreas abiertas y semiabiertas, arbolados dispersos, vegetación secundaria, borde y ecotonos de bosques'],
        'comida': ['insectos grandes, lagartijas, ranas, pequeños mamíferos, peces, frutos y semillas']
    },
    'momoto_corona_café': {
        'ojos': ['cafes'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['verde'],
        'vientre': ['verde', 'amarillo'],
        'cabeza': ['roja'],
        'garganta': [],
        'espalda': [],
        'alas': ['azules', 'verdes'],
        'cola': ['verde', 'azul'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [32],
        'habitat': ['bosques y matorrales'],
        'comida': ['frutos e insectos']
    },
    'mosquero_de_hammond': {
        'ojos': ['negro'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['gris'],
        'vientre': [],
        'cabeza': ['gris'],
        'garganta': ['gris'],
        'espalda': [],
        'alas': [],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [14],
        'habitat': ['bosques templados (bosque de pino, pino-encino)'],
        'comida': ['insectos']
    },
    'mulato_azul': {
        'ojos': ['rojos'],
        'pico': ['gris'],
        'antifaz': [],
        'frente': [],
        'loras': ['negras'],
        'cuerpo': ['azul'],
        'nuca': [],
        'auriculares': ['negros'],
        'pecho': ['azul'],
        'vientre': [],
        'cabeza': ['azul'],
        'garganta': [],
        'espalda': [],
        'alas': [],
        'cola': ['roja'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [25],
        'habitat': ['sotobosques densos de bosques de pino y bosques de encino, matorrales y bosques espinosos (generalmente asociado con cuerpos de agua)'],
        'comida': ['insectos y frutos']
    },
    'papamoscas_llanero': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['gris'],
        'vientre': [],
        'cabeza': ['gris'],
        'garganta': ['gris'],
        'espalda': ['gris'],
        'alas': [],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [19],
        'habitat': ['áreas abiertas áridas y semiáridas (planicies costeras, desiertos, matorrales y bosques con árboles dispersos)'],
        'comida': ['insectos, arañas y en ocasiones frutos']
    },
    'reyezuelo_de_rojo': {
        'ojos': ['negros'],
        'pico': ['gris'],
        'antifaz': [],
        'frente': [],
        'loras': ['blancas'],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['blanco'],
        'vientre': ['blanco'],
        'cabeza': ['roja', 'gris'],
        'garganta': ['blanca'],
        'espalda': ['gris'],
        'alas': ['negras'],
        'cola': ['negra'],
        'patas': ['amarillas'],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [11],
        'habitat': ['bosques y matorrales en general'],
        'comida': ['insectos, pequeñas arañas y en ocasiones consume frutos, semillas y sabia']
    },
    'semillero_de_collar_reproductivo': {
        'ojos': ['negros'],
        'pico': ['gris'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['rojo'],
        'cabeza': ['negra'],
        'garganta': ['amarilla'],
        'espalda': ['cafe'],
        'alas': ['cafes'],
        'cola': ['cafe'],
        'patas': [],
        'tarso': [],
        'rabadilla': ['roja'],
        'tamanio': [11],
        'habitat': ['pastizales abiertos, matorrales, bosques abiertos y caminos suburbanos y rurales'],
        'comida': ['semillas e insectos']
    },
    'tangara_capucha_roja': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['amarillo'],
        'vientre': ['amarillo'],
        'cabeza': ['amarilla'],
        'garganta': [],
        'espalda': [],
        'alas': ['negras'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [18],
        'habitat': ['bosques templados (pino, pino-encino, encino)'],
        'comida': ['insectos y frutos pequeños']
    },
    'tirano_gritón': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['gris'],
        'vientre': ['amarillo'],
        'cabeza': ['gris'],
        'garganta': [],
        'espalda': ['verde'],
        'alas': ['cafes'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [22],
        'habitat': ['zonas abiertas con vegetación dispersa y bosques de pino-encino'],
        'comida': ['insectos y ocasionalmente frutos']
    },
    'tirano_pálido': {
        'ojos': ['negros'],
        'pico': ['negro'],
        'antifaz': [],
        'frente': [],
        'loras': ['negras'],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['gris'],
        'vientre': ['amarillo'],
        'cabeza': ['gris'],
        'garganta': ['gris'],
        'espalda': ['gris'],
        'alas': ['cafes', 'grises'],
        'cola': ['negra'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [21],
        'habitat': ['bosques abiertos y semiabiertos y caminos rurales, y huertos'],
        'comida': ['insectos y en ocasiones consume milpiés, arañas y frutos (sobre todo en la época migratoria)']
    },
    'vireo_plomizo': {
        'ojos': ['negros'],
        'pico': ['gris'],
        'antifaz': [],
        'frente': [],
        'loras': [],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['blanco'],
        'vientre': ['gris'],
        'cabeza': ['gris'],
        'garganta': [],
        'espalda': ['gris'],
        'alas': ['grises'],
        'cola': ['gris'],
        'patas': [],
        'tarso': [],
        'rabadilla': [],
        'tamanio': [14],
        'habitat': ['Bosques abiertos y semiabiertos de pino-encino y arbolados en general'],
        'comida': ['insectos']
    },
    'zorzal_cola_rufa': {
        'ojos': ['negros'],
        'pico': [],
        'antifaz': [],
        'frente': [],
        'loras': ['blancas'],
        'cuerpo': [],
        'nuca': [],
        'auriculares': [],
        'pecho': ['blanco'],
        'vientre': [],
        'cabeza': ['cafe'],
        'garganta': ['blanca'],
        'espalda': [],
        'alas': ['cafes'],
        'cola': ['roja'],
        'patas': ['rosa'],
        'tarso': ['rosa'],
        'rabadilla': [],
        'tamanio': [17],
        'habitat': ['bosques templados como pino-encino, encino, abeto con sotobosques densos'],
        'comida': ['insectos y frutos']
    },
    # '': {
    #     'ojos': [],
    #     'pico': [],
    #     'antifaz': [],
    #     'frente': [],
    #     'loras': [],
    #     'cuerpo': [],
    #     'nuca': [],
    #     'auriculares': [],
    #     'pecho': [],
    #     'vientre': [],
    #     'cabeza': [],
    #     'garganta': [],
    #     'espalda': [],
    #     'alas': [],
    #     'cola': [],
    #     'patas': [],
    #     'tarso': [],
    #     'rabadilla': [],
    #     'tamanio': [],
    #     'habitat': [],
    #     'comida': []
    # },
}